# 02. SQL Sanity Checks & Data Validation 
Goal:
- Validate **every feature** using MIN / MAX / AVG
- Detect impossible or suspicious values
- Build **business trust** in data before modeling

## 1. Database Connection

In [3]:
import pandas as pd
from sqlalchemy import create_engine
import sqlite3
engine= sqlite3.connect("wine_quality.db")

## 2. Row Count Check

In [4]:
pd.read_sql('SELECT COUNT(*) AS total_rows FROM wine_cleaned;', engine)

   total_rows
0        5320

### Observation
- Confirms successful ingestion of both red and white wine datasets
- Acts as a baseline for all further analysis

## 3. Quality Distribution

In [5]:
pd.read_sql('''SELECT quality, COUNT(*) AS count FROM wine_cleaned GROUP BY quality ORDER BY quality;''', engine)

   quality  count
0        3     30
1        4    206
2        5   1752
3        6   2323
4        7    856
5        8    148
6        9      5

### Observation
- Reveals class imbalance
- Middle quality scores dominate the dataset

## 4. Full Feature Range Validation

In [14]:
pd.read_sql('''SELECT MIN(fixed_acidity) AS min_fixed_acidity, MAX(fixed_acidity) AS max_fixed_acidity, AVG(fixed_acidity) AS avg_fixed_acidity,
MIN(volatile_acidity) AS min_volatile_acidity, MAX(volatile_acidity) AS max_volatile_acidity, AVG(volatile_acidity) AS avg_volatile_acidity,
MIN(citric_acid) AS min_citric_acid, MAX(citric_acid) AS max_citric_acid, AVG(citric_acid) AS avg_citric_acid
FROM wine_cleaned;''', engine)

,min_fixed_acidity,max_fixed_acidity,avg_fixed_acidity,min_volatile_acidity,max_volatile_acidity,avg_volatile_acidity,min_citric_acid,max_citric_acid,avg_citric_acid
0,3.8,15.9,7.215179,0.08,1.58,0.34413,0.0,1.66,0.318494

In [11]:
pd.read_sql(""" SELECT MIN(chlorides) AS min_chlorides, MAX(chlorides) AS max_chlorides, AVG(chlorides) AS avg_chlorides,
MIN(free_sulfur_dioxide) AS min_free_sulfur_dioxide, MAX(free_sulfur_dioxide) AS max_free_sulfur_dioxide, AVG(free_sulfur_dioxide) AS avg_free_sulfur_dioxide,
MIN(total_sulfur_dioxide) AS min_total_sulfur_dioxide, MAX(total_sulfur_dioxide) AS max_total_sulfur_dioxide, AVG(total_sulfur_dioxide) AS avg_total_sulfur_dioxide,
MIN(sulphates) AS min_sulphates, MAX(sulphates) AS max_sulphates, AVG(sulphates) AS avg_sulphates
FROM wine_cleaned""",
engine)

,min_chlorides,max_chlorides,avg_chlorides,min_free_sulfur_dioxide,max_free_sulfur_dioxide,avg_free_sulfur_dioxide,min_total_sulfur_dioxide,max_total_sulfur_dioxide,avg_total_sulfur_dioxide,min_sulphates,max_sulphates,avg_sulphates
0,0.009,0.611,0.05669,1.0,289.0,30.036654,6.0,440.0,114.109023,0.22,2.0,0.533357

In [12]:
pd.read_sql(""" SELECT MIN(residual_sugar) AS min_residual_sugar, MAX(residual_sugar) AS max_residual_sugar, AVG(residual_sugar) AS avg_residual_sugar,
MIN(density) AS min_density, MAX(density) AS max_density, AVG(density) AS avg_density,
MIN(pH) AS min_pH, MAX(pH) AS max_pH, AVG(pH) AS avg_pH,
MIN(alcohol) AS min_alcohol, MAX(alcohol) AS max_alcohol, AVG(alcohol) AS avg_alcohol
FROM wine_cleaned;""", engine)

,min_residual_sugar,max_residual_sugar,avg_residual_sugar,min_density,max_density,avg_density,min_pH,max_pH,avg_pH,min_alcohol,max_alcohol,avg_alcohol
0,0.6,65.8,5.048477,0.98711,1.03898,0.994535,2.72,4.01,3.224664,8.0,14.9,10.549241

### Observation
- All acidity-related features fall within chemically valid ranges
- Sulphur_Dioxide,sulphates,chlorides having ranges which are general in wine making industries.
- Ph,alcohol,density,,residual_sugars are chemically valid ranges for a wine.

## 5. NULL Checks

In [15]:
pd.read_sql('''SELECT
SUM(CASE WHEN fixed_acidity IS NULL THEN 1 ELSE 0 END) AS fixed_acidity_nulls,
SUM(CASE WHEN volatile_acidity IS NULL THEN 1 ELSE 0 END) AS volatile_acidity_nulls,
SUM(CASE WHEN citric_acid IS NULL THEN 1 ELSE 0 END) AS citric_acid_nulls,
SUM(CASE WHEN residual_sugar IS NULL THEN 1 ELSE 0 END) AS residual_sugar_nulls,
SUM(CASE WHEN chlorides IS NULL THEN 1 ELSE 0 END) AS chlorides_nulls,
SUM(CASE WHEN free_sulfur_dioxide IS NULL THEN 1 ELSE 0 END) AS free_sulfur_dioxide_nulls,
SUM(CASE WHEN total_sulfur_dioxide IS NULL THEN 1 ELSE 0 END) AS total_sulfur_dioxide_nulls,
SUM(CASE WHEN density IS NULL THEN 1 ELSE 0 END) AS density_nulls,
SUM(CASE WHEN pH IS NULL THEN 1 ELSE 0 END) AS pH_nulls,
SUM(CASE WHEN sulphates IS NULL THEN 1 ELSE 0 END) AS sulphates_nulls,
SUM(CASE WHEN alcohol IS NULL THEN 1 ELSE 0 END) AS alcohol_nulls,
SUM(CASE WHEN quality IS NULL THEN 1 ELSE 0 END) AS quality_nulls
FROM wine_cleaned;''', engine)

,fixed_acidity_nulls,volatile_acidity_nulls,citric_acid_nulls,residual_sugar_nulls,chlorides_nulls,free_sulfur_dioxide_nulls,total_sulfur_dioxide_nulls,density_nulls,pH_nulls,sulphates_nulls,alcohol_nulls,quality_nulls
0,0,0,0,0,0,0,0,0,0,0,0,0

### Observation
- No nulls exist in all the features/columns.

## Final Conclusion
- All columns validated successfully
- No missing or invalid values
- Class imbalance is very high.A reliable metric should be choosen.
- Dataset is reliable for modeling